phone: "05444957349"
whatsapp: https://wa.me/905444957349?text=Merhaba%2C%20Karma%20Textile%20toptan%20ürünler%20hakkında%20bilgi%20almak%20istiyorum.
instagram: https://www.instagram.com/karmatekstil/
